# Generated by Django 3.1.2 on 2023-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slugline', models.CharField(max_length=200)),
                ('seo_title', models.CharField(max_length=200)),
            ],
        ),
    ]
