# Generated by Django 4.2.7 on 2023-11-16 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="content_title",
            new_name="title",
        ),
    ]
